# Generated by Django 4.2.23 on 2025-07-24 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_phone_number_userloggedindevices'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userloggedindevices',
            old_name='last_login',
            new_name='created_at',
        ),
    ]
