# Generated by Django 4.2.23 on 2025-07-24 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_last_login_userloggedindevices_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userloggedindevices',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
