# Generated by Django 4.2.23 on 2025-07-23 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0003_threadsubscriber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='is_deleted',
        ),
        migrations.RemoveField(
            model_name='thread',
            name='is_deleted',
        ),
    ]
