# Generated by Django 4.2.23 on 2025-07-23 15:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0004_remove_comment_is_deleted_remove_thread_is_deleted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='thread',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(5), django.core.validators.MaxLengthValidator(300)]),
        ),
        migrations.AlterField(
            model_name='thread',
            name='title',
            field=models.CharField(validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(100)]),
        ),
    ]
