# Generated by Django 4.2.23 on 2025-07-23 18:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('thread', '0005_rename_comment_comment_text_alter_thread_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='subscribers',
            field=models.ManyToManyField(related_name='thread_subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ThreadSubscriber',
        ),
    ]
