# Generated by Django 4.2.23 on 2025-07-23 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_notificationchannelpreference_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationchannelpreference',
            name='enabled',
            field=models.BooleanField(),
        ),
    ]
